apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmockdatabases.quickstart.crossplane.io
spec:
  group: quickstart.crossplane.io
  names:
    kind: XMockDatabase
    plural: xmockdatabases
  claimNames:
    kind: MockDatabase
    plural: mockdatabases
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: |
                The specification for how this database should be
                deployed.
              properties:
                parameters:
                  type: object
                  description: |
                    The parameters indicating how this database should
                    be configured.
                  properties:
                    region:
                      type: string
                      enum:
                        - us-east
                        - us-west
                      description: |
                        The geographic region in which this database
                        should be deployed.
                    size:
                      type: string
                      enum:
                        - small
                        - medium
                        - large
                      description: |
                        The machine size for this database.
                    storage:
                      type: integer
                      description: |
                        The storage size for this database in GB.
                  required:
                    - region
                    - size
                    - storage
              required:
                - parameters